#!/usr/bin/python

import sys, os
import exceptions
cwd = os.path.dirname(os.path.abspath(__file__))
sys.path.extend([os.path.join(cwd, '..')])
from common import *
import cgilib
import cgi
import cgitb
import subprocess
cgitb.enable()

args = cgi.FieldStorage()
path, content = args.getfirst('path', ''), args.getfirst('content', "")
if path and content:
    write(path, content)
if not content:
    content = safe_read(path)
print(cgilib.render('res/edit.html', path=path, content=content))
